# =======================================
# NOME DA APLICAÇÃO
# =======================================
spring.application.name=mindwell-api

# =======================================
# CONEXÃO COM O BANCO DE DADOS (Docker)
# =======================================
spring.datasource.url=jdbc:postgresql://localhost:5432/mindwell_db
spring.datasource.username=docker
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================================
# CONFIGURAÇÃO DO HIBERNATE (JPA)
# =======================================
# "update": Cria as tabelas se não existirem, e atualiza se mudarem (não apaga dados!)
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no terminal (ótimo para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect